### PR TITLE
fixed repository comment is hidden

### LINKED ISSUE #17: Repository comment is still hidden after successful entry
**Describe the bug**
When I insert comment, it doesn't automatically appear on the list of comment below. And also the comment box is not emptied after the successful entry.

It make me confuse, as i cant actually see if the comment has been created created or not, so i would keep on pressing the button or I need to go out to Projects and walk my way in back to see the comment.

**To Reproduce**
1. Go to 'Projects'
2. Click on any repository
3. Scroll down to comment section
4. Enter a comment and click Post Comment
5. Error: Comment doesn't appear below

**Expected behavior**
1. Click Post Comment
2. On success, created comment appear at the top of the list.
3. On success, the comment input box is empty.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by HaziqRauf**
Change the primary key to the composite primary key, adding reset form method to empty the comment section. Close #17

### CODE REVIEW

File: src/pages/User/Repository.vue [hunk 1]
```diff
@@ -161,18 +161,33 @@ export default {
...
+      this.$store.dispatch('GetRepositoryNote', this.$route.params.id);
+    },
     onClickComment() {
       this.$store.dispatch('AddRepositoryNote', {
         id: this.repository.id,
         from: this.repository.user.uuid,
         text: this.form.comment,
+      })
+      .then((res)=>{
+        this.loadComment();
```
Comment (iqbalbaharum) [inline src/pages/User/Repository.vue:179]: Based on the design, there is no need to run `loadComment`.

If you look at `module/repository.js` Line 128.

```
AddRepositoryNote({ rootState }, data) {
      data.from = rootState.user.userId
      console.log(data)
      return new Promise((resolve, reject) => {
        this.$repository.repository.createNote(data.id, data.from, data.to, data.text)
          .then(res => {
            Note.insert(res.data)
            resolve(res.data)
          })
          .catch(err => {
            reject(err)
          })
      })
    }
```

Every time it has successfully create a comment, it would insert the data to the vuex database. So, its a redundant to call `loadComment` back.

**Review by iqbalbaharum — CHANGES_REQUESTED** [review]

**Comment by HaziqRauf** [comment]
Latest Commit

Remove the load comment

**Review by iqbalbaharum — APPROVED** [review]
